# Traefik Static Configuration
api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  web:
    address: ":8000"
  traefik:
    address: ":8080"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: "microservice_network"
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: json

accessLog:
  format: json

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# Enable ping endpoint for health checks
ping:
  entryPoint: "traefik" 